spring:
  profiles:
    active: h2dev


  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
graphql:
  servlet:
    cors-enabled: true
    enabled: true
    mapping: /graphql

image:
  path: image


