server:
  port: 8080

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform:
  datasource:
    url: jdbc:mysql://****/movie_test
    name: ****
    password: ****
    username: movie_share



dataInit: false